; ===========================================
; Custom Echo Stress 설정 파일 (인스턴스 2)
; ===========================================

[Stress]
ServerIp=127.0.0.1
Port=6000
ClientCount=1000
DisconnectTest=1
OverSendCount=100
LoopDelayMs=1

;---------------------------------------------------------------------
; --- 아래 항목은 기본값 유지 권장 ---
;---------------------------------------------------------------------
ReconnectIntervalMs=1000
EchoTimeoutMs=500
TestDurationSec=0
MonitorPort=9093
